python2.7 VCF2SM.py -i ../data/sample_vcf/myGBSGenos_trifida_mergedSNPs_mergedTaxa_chr3.vcf \
                    -o sweetpotato_trifida_ch.vcf\
                    -d 20\
                    -a AD\
                    -g BT\
                    -1 Beauregard\
                    -2 Tanzania\
                    -S ./src/SuperMASSA.py\
                    -I f1\
                    -M 2:6\
                    -f 2:6\
                    -p 0.80\
                    -n 0.50\
                    -c 0.50\
                    -t 16